POST http://localhost:3000/api-pwa/services
Content-Type: application/json

{
      "name": "Decoração",
      "description": "Escolha a decoração para sua festa, e nós a montamos.",
      "price": 1400,
      "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
    }

###

GET http://localhost:3000/api-pwa/services

###

GET http://localhost:3000/api-pwa/services/66d14e23054ff95f8ef758a6

###

DELETE http://localhost:3000/api-pwa/services/66e5e0d1729ae0a2d680310b


###

PUT  http://localhost:3000/api-pwa/services/66d14f61a797cdf9c1995a97
Content-Type: application/json

{
    "name ":"Teste atualizacao3",
    "description":"duas descricao",
    "price": 2800,
    "image":"httpF193221%2Fprofile%2Foriginal%2Fpitbull-p.jpg%36YfyM&tbnid=d1UWMuQqzjxKcM&vet=12ahUKEwio9O7vp5uIAxWKLrkGHWYyPPkQM3oFCIEBEAA..i&w=640&h=640&hcb=2&ved=2ahUKEwio9O7vp5uIAxWKLrkGHWYyPPkQM3oFCIEBEAA"
}

###

POST http://localhost:3000/api-pwa/parties
Content-Type: application/json

{
    "title": "Firt partie 2",
    "author": "Kashi",
    "description": "Vem com tudo",
    "budget": 3000,
    "image": "https://ovicio.com.br/wp-content/uploads/2021/11/20211119-ovicio-one-piece-cosplay-luffy.jpg",
    "services": [
        {
            "name ":"Alguma servico1",
            "description":"duas descricao",
            "price": 1000,
            "image":"httpF193221%2Fprofile%2Foriginal%2Fpitbull-p.jpg%36YfyM&tbnid=d1UWMuQqzjxKcM&vet=12ahUKEwio9O7vp5uIAxWKLrkGHWYyPPkQM3oFCIEBEAA..i&w=640&h=640&hcb=2&ved=2ahUKEwio9O7vp5uIAxWKLrkGHWYyPPkQM3oFCIEBEAA"
        },
        {
            "name ":"Alguma servico2",
            "description":"duas descricao",
            "price": 1600,
            "image":"httpF193221%2Fprofile%2Foriginal%2Fpitbull-p.jpg%36YfyM&tbnid=d1UWMuQqzjxKcM&vet=12ahUKEwio9O7vp5uIAxWKLrkGHWYyPPkQM3oFCIEBEAA..i&w=640&h=640&hcb=2&ved=2ahUKEwio9O7vp5uIAxWKLrkGHWYyPPkQM3oFCIEBEAA"
        }
    ]
    
}

###

GET http://localhost:3000/api-pwa/parties

###

GET http://localhost:3000/api-pwa/parties/66d127e409ca046c9e9809b8


###

DELETE http://localhost:3000/api-pwa/parties/66d14fa7c09bc8f28eeec63b


###

PUT http://localhost:3000/api-pwa/parties/66d14fa7c09bc8f28eeec63b
Content-Type: application/json

{
    "title": "Firt partie 2",
    "author": "marquinhos",
    "description": "Vem com tudo",
    "budget": 10000,
    "image": "httpF193221%2Fprofile%2Foriginal%2Fpitbull-p.jpg%36YfyM&tbnid=d1UWMuQqzjxKcM&vet=12ahUKEwio9O7vp5uIAxWKLrkGHWYyPPkQM3oFCIEBEAA..i&w=640&h=640&hcb=2&ved=2ahUKEwio9O7vp5uIAxWKLrkGHWYyPPkQM3oFCIEBEAA",
    "services": [
        {
            "name ":"Alguma servico1",
            "description":"duas descricao",
            "price": 1000,
            "image":"httpF193221%2Fprofile%2Foriginal%2Fpitbull-p.jpg%36YfyM&tbnid=d1UWMuQqzjxKcM&vet=12ahUKEwio9O7vp5uIAxWKLrkGHWYyPPkQM3oFCIEBEAA..i&w=640&h=640&hcb=2&ved=2ahUKEwio9O7vp5uIAxWKLrkGHWYyPPkQM3oFCIEBEAA"
        },
        {
            "name ":"Alguma servico2",
            "description":"duas descricao",
            "price": 1000,
            "image":"httpF193221%2Fprofile%2Foriginal%2Fpitbull-p.jpg%36YfyM&tbnid=d1UWMuQqzjxKcM&vet=12ahUKEwio9O7vp5uIAxWKLrkGHWYyPPkQM3oFCIEBEAA..i&w=640&h=640&hcb=2&ved=2ahUKEwio9O7vp5uIAxWKLrkGHWYyPPkQM3oFCIEBEAA"
        }
    ]
    
}